### PR TITLE
WKwebview bug fix & version bump

### LINKED ISSUE #26: Apple warning
> ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview). 

image

### PR DESCRIPTION
**Pull request by tiwaripoonam**
Resolves #26

### CODE REVIEW

File: BlotoutAnalytics/Utilities/BOServerDataConverter.m [hunk 1]
```diff
@@ -57,14 +58,11 @@ +(NSDictionary*)recordAppInformation {
       int timeoOffset = [BOAUtilities getCurrentTimezoneOffsetInMin];
       [appInfo setObject:[NSNumber numberWithInt:timeoOffset] forKey:@"timeZoneOffset"];
       
-      //UIWebView Depriciated , need to handle it with WKWebView
       dispatch_async(dispatch_get_main_queue(), ^{
-      UIWebView* webView = [[UIWebView alloc] initWithFrame:CGRectZero];
-     
-      NSString* userAgent = [webView stringByEvaluatingJavaScriptFromString:@"navigator.userAgent"];
-          
+      NSString *userAgent = [[WKWebView new] valueForKey:@"userAgent"];
```
Comment (NejcZdovc) [inline BlotoutAnalytics/Utilities/BOServerDataConverter.m:62]: is `WKWebView` always available or is it possible that this would be not set (if sdk is called in some other thread for example)?

**Review by NejcZdovc — APPROVED** [review]

File: BlotoutAnalytics/Utilities/BOServerDataConverter.m (hunk 1 above)
Comment (tiwaripoonam) [reply BlotoutAnalytics/Utilities/BOServerDataConverter.m:62]: this is explicitly called on the main thread, so that would not be an issue.
